site_name: wiredflow
site_url: https://wiredflow.readthedocs.io/en/latest/
site_author: Wiredhut team
repo_url: https://github.com/wiredhut/wiredflow

nav:
    - Home: index.md
    - Common description:
          - 'Why you should try wiredflow': 'common/faq.md'
          - 'Functionality review': 'common/functionality_review.md'
          - 'Features and limitations': 'common/features_and_limitations.md'
          - 'Scalability issues': 'common/scalability.md'
          - 'Scalability: tokenization': 'common/scalability_tokenization.md'
          - 'Scalability: remote launch': 'common/scalability_remote.md'
          - 'Wiredflow is your friend': 'common/friend.md'
          - 'Architecture of wiredflow (for developers)': 'common/architecture.md'
    - Tutorials:
          - 'Quick start': 'tutorial/1_quick_start.md'
          - 'HTTP connector': 'tutorial/2_http.md'
          - 'MQTT connector': 'tutorial/3_mqtt.md'
          - 'Complex service': 'tutorial/4_service_with_pipelines.md'
          - 'Storages': 'tutorial/5_storage.md'
          - 'MongoDB integration': 'tutorial/6_mongo.md'
          - 'Customization': 'tutorial/7_customization.md'
          - 'Threads or processes': 'tutorial/8_threads_and_processes.md'
          - 'Tokenization': 'tutorial/9_tokenization.md'
          - 'Remote launch': 'tutorial/10_remote.md'
          - 'Wiredflow for development': 'tutorial/11_development.md'
    - Additional:
          - 'Contribution': 'additional/contributing.md'
          - 'Publications': 'additional/publications.md'
          - 'Commercial use cases': 'additional/real_cases.md'
          - 'Roadmap': 'additional/roadmap.md'
          - 'About us': 'additional/about.md'
theme:
    name: readthedocs
    logo: https://raw.githubusercontent.com/wiredhut/wiredflow/main/docs/media/wiredflow_inverse.png
