site_name: wiredflow
site_url: https://wiredflow.readthedocs.io/en/latest/
site_author: Wiredhut team
repo_url: https://github.com/wiredhut/wiredflow

nav:
    - Home: index.md
    - Common description:
          - 'Features and limitations': 'common/features_and_limitations.md'
          - 'Scalability issues': 'common/scalability.md'
          - 'Scalability: tokenization': 'common/scalability_tokenization.md'
          - 'Scalability: remote launch': 'common/scalability_remote.md'
          - 'Customization': 'common/customization.md'
    - Tutorials:
          - 'Quick start': 'tutorial/1_quick_start.md'
          - 'Several pipelines service': 'tutorial/2_service_with_pipelines.md'
          - 'Threads or processes': 'tutorial/3_threads_and_processes.md'
    - Additional:
          - 'Contribution': 'additional/contributing.md'
          - 'Publications': 'additional/publications.md'
          - 'Commercial use cases': 'additional/real_cases.md'
          - 'About us': 'additional/about.md'
theme:
    name: readthedocs
    logo: https://raw.githubusercontent.com/wiredhut/wiredflow/main/docs/media/wiredflow_inverse.png
